import type { Metadata } from "next";
import Sidebar from "./components/Sidebar";
import Navbar from "./components/Navbar";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import { Toaster } from "react-hot-toast";
export const metadata: Metadata = {
  title: "Saif Ali Khan | Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-row">
      {/* sidebar  */}
      <div className="hidden lg:flex w-1/5">
        <Sidebar />
      </div>
      {/* navbar and main section  */}
      <div className="w-full lg:w-4/5  ">
        <Navbar />

        <main className="h-[calc(100vh-62px)] overflow-y-auto">
          {" "}
          <ReactQueryProvider>{children}</ReactQueryProvider>
        </main>

        <Toaster />
      </div>
    </div>
  );
}
